.\"	$adsuck$
.\"
.\" Copyright (c) 2009 Marco Peereboom <marco@peereboom.us>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt ADSUCK 1
.Os
.Sh NAME
.Nm adsuck
.Nd DNS blacklisting daemon
.Sh SYNOPSIS
.Nm adsuck
.Bk -words
.Op Fl Ddv
.Op Fl c Ar directory
.Op Fl f Ar resolv.conf
.Op Fl l Ar listen
.Op Fl p Ar port
.Op Fl u Ar user
.Ar hostsfile ...
.Ek
.Sh DESCRIPTION
.Nm adsuck
is a small DNS server that spoofs blacklisted addresses and forwards all other
queries.
The idea is to be able to prevent connections to undesirable sites such as ad
servers, crawlers and other nasties.
It can be used locally, for the road warrior, or on the network perimeter in
order to protect machines from malicious sites.
.Pp
.Nm
replies to bad addresses with a spoofed DNS packet that has the NXdomain
flag set.
This in effect prevents the application that is resolving the address from
trying to connect to this address.
Addresses that are not matched are forwarded to the normal nameserver,
as provided by
.Xr resolv.conf 5 .
.Pp
Note that when applications try to be smart
and resolve an address with the local domain name appended,
it will still spoof the answer.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar directory
This is the chroot directory.
If it is not specified, it uses the home_dir entry from
.Pa /etc/passwd .
.It Fl D
Do not daemonize.
.It Fl d
Enable debug output.
.It Fl f Ar resolv.conf
This is a standard formatted resolv.conf file that contains the name server that
can resolve non-blacklisted entries.
.It Fl l Ar listen
This is the address
.Nm
will listen on.
The default is all IP addresses.
.It Fl p Ar port
This is the port number that
.Nm
will bind to.
The default is 53.
.It Fl r Ar regexfile
Filename of a file that contains one regex expression per line; e.g
banner|ads|stat|track|click.
When matched the DNS response will be spoofed.
The regex engine runs before the hostsfile match.
.It Fl u Ar user
This is the user that
.Nm
will drop privileges to after it binds to the listen address.
The default is _adsuck.
.It Fl v
Enable verbose output.
.It Ar hostsfile
This is a standard formatted hostsfile that contains all blacklisted entries.
Examples of good blacklist files can be found at
.Bd -literal
http://rlwpx.free.fr/WPFF/hosts.htm and
http://www.mvps.org/winhelp2002/
.Ed
.El
.Pp
Sending
.Nm
a SIGHUP signal will cause it to reread the resolv.conf file.
A SIGUSR1 signal will cause it to reread all hostsfiles.
.Sh FILES
.Bl -tag -width "resolv.confXXX"
.It Pa hostsfile
Blacklist entries in standard hostsfile format.
The entries must point to 127.0.0.1.
E.g. 127.0.0.1 badsite.com
.It Pa resolv.conf
Standard resolv.conf file that contain the actual resolving
nameserver and options.
.El
.Sh SEE ALSO
.Xr resolv.conf 5
.Sh HISTORY
.Nm
was written to do some smarter ad blocking without using individual browser
components and to avoid lengthy hostsfile lookups.
.Sh AUTHORS
.An -nosplit
.Pp
.Nm
was written by
.An Marco Peereboom Aq marco@peereboom.us .
.Sh BUGS
Currently
.Nm
depends on ldns.
